### ISSUE TITLE
Compilation error when calling processOne() in ordered Queue sample

### ISSUE THREAD

**Issue by MH2033** [wqking/eventpp#30] opened 2021-11-01 08:03 UTC
Replacing process() with processOne() in the sample code that you provided for OrderedQueueList, will cause a compilation error.

The code: 
```

#include <iostream>
#include "eventpp/eventqueue.h"
#include "eventpp/utilities/orderedqueuelist.h"
struct MyEvent
{
	int e;
	int priority;
};

// The comparison function object used by eventpp::OrderedQueueList.
// The function compares the event by priority.
struct MyCompare
{
	template <typename T>
	bool operator() (const T & a, const T & b) const {
		return std::get<0>(a.arguments).priority > std::get<0>(b.arguments).priority;
	}
};

// Define the EventQueue policy
struct MyPolicy
{
	template <typename Item>
	using QueueList = eventpp::OrderedQueueList<Item, MyCompare >;

	static int getEvent(const MyEvent & event) {
		return event.e;
	}
};

int main()
{
	using EQ = eventpp::EventQueue<int, void(const MyEvent &), MyPolicy>;
	EQ queue;

	queue.appendListener(3, [](const MyEvent & event) {
		std::cout << "Get event " << event.e << "(should be 3)." << " priority: " << event.priority << std::endl;
	});
	queue.appendListener(5, [](const MyEvent & event) {
		std::cout << "Get event " << event.e << "(should be 5)." << " priority: " << event.priority << std::endl;
	});
	queue.appendListener(7, [](const MyEvent & event) {
		std::cout << "Get event " << event.e << "(should be 7)." << " priority: " << event.priority << std::endl;
	});

	// Add an event, the first number 5 is the event type, the second number 100 is the priority.
	// After the queue processes, the events will be processed from higher priority to lower priority.
	queue.enqueue(MyEvent{ 5, 100 });
	queue.enqueue(MyEvent{ 5, 200 });
	queue.enqueue(MyEvent{ 7, 300 });
	queue.enqueue(MyEvent{ 7, 400 });
	queue.enqueue(MyEvent{ 3, 500 });
	queue.enqueue(MyEvent{ 3, 600 });

	queue.processOne();
}
```

Error message:

![image](https://user-images.githubusercontent.com/5557100/139640709-b10d4ea0-1a7c-4096-8c83-baa3c7604fdb.png)

Compilation flags:

"-std=c++11 -O0"

**Comment by wqking** [comment] 2021-11-01 08:27
Fixed in commit 32197674a4519835704858bdc2250be159a9eceb
It's intended that `OrderedQueueList` inherits from `std::list` in private manner and only expose necessary functions as public. The error was caused by that function `front` was not exposed.

Warning: if you need to use `processIf` on `OrderedQueueList`, since `OrderedQueueList` sorts the full list upon `splice`, and `processIf` calls `splice` in loop, the performance may be bad. `process` and `processOne` should be fine.

**Closed** 2021-11-01 13:05 UTC
