### ISSUE TITLE
Inheritance from EventDispatcher doesn't compile

### ISSUE THREAD

**Issue by gdeverlant** [wqking/eventpp#2] opened 2019-03-07 18:53 UTC
```
struct MyClass: Class1, EventDispatcher<int, void()> {
etc....
}
```

generates compilation error

> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2988: unrecognizable template declaration/definition (compiling source file sources\MonaTiny.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(282): note: see reference to class template instantiation 'eventpp::internal_::EventDispatcherBase<EventType,ReturnType(Args...),PoliciesType,MixinRoot_>' being compiled (compiling source file sources\MonaTiny.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2143: syntax error: missing ')' before 'this' (compiling source file sources\MonaTiny.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2143: syntax error: missing ';' before 'this' (compiling source file sources\MonaTiny.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2238: unexpected token(s) preceding ';' (compiling source file sources\MonaTiny.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2059: syntax error: 'this' (compiling source file sources\MonaTiny.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2059: syntax error: ')' (compiling source file sources\MonaTiny.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(262): error C2334: unexpected token(s) preceding ':'; skipping apparent function body (compiling source file sources\MonaTiny.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(30): fatal error C1075: the left brace '{' was unmatched at the end of the file (compiling source file sources\MonaTiny.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2988: unrecognizable template declaration/definition (compiling source file sources\main.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(282): note: see reference to class template instantiation 'eventpp::internal_::EventDispatcherBase<EventType,ReturnType(Args...),PoliciesType,MixinRoot_>' being compiled (compiling source file sources\main.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2143: syntax error: missing ')' before 'this' (compiling source file sources\main.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2143: syntax error: missing ';' before 'this' (compiling source file sources\main.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2238: unexpected token(s) preceding ';' (compiling source file sources\main.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2059: syntax error: 'this' (compiling source file sources\main.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(248): error C2059: syntax error: ')' (compiling source file sources\main.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(262): error C2334: unexpected token(s) preceding ':'; skipping apparent function body (compiling source file sources\main.cpp)
> 1>g:\programming\c++\monaserver2\eventdispatcher\eventpp\include\eventpp\eventdispatcher.h(30): fatal error C1075: the left brace '{' was unmatched at the end of the file (compiling source file sources\main.cpp)

**Comment by wqking** [comment] 2019-03-08 00:44
Hi which compiler and the version do you use? I can't reproduce the problem in VC 2017 and gcc 7.2.
Did you miss ';' after your MyClass declaration?
My test code:

```
struct Class1 {};
struct MyClass: Class1, eventpp::EventDispatcher<int, void()> {
};
```

**Comment by gdeverlant** [comment] 2019-03-08 12:25
I'm using visual studio 2017 community edition.

**Comment by wqking** [comment] 2019-03-08 14:38
I just notice that there is no document on how to integrate `eventpp` to the projects, sorry, I will add the document.
You don't need to link to it as any library, you just add the `include` path in `eventpp` to your project, then you can use it. `eventpp` is header only, you don't need to link to it.

**Comment by gdeverlant** [comment] 2019-03-08 15:58
That is really kind of your my dear. I deeply appreciate it.

**Comment by wqking** [comment] 2019-03-09 07:39
I added the document, it's as simple as I replied in previous message.
This issue is not a problem, I will close it.

**Closed by wqking** 2019-03-09 07:39 UTC
